import { NeuralModelDefinition } from "./types";

export const MODEL_REGISTRY: NeuralModelDefinition[] = [
  // ==========================================
  // 1. TEXT-TO-IMAGE (T2I)
  // ==========================================
  {
    id: "flux-dev",
    name: "Flux Dev",
    developer: "Black Forest Labs",
    endpoint: "/flux-dev",
    category: "t2i",
    description: "Industry standard open-weight diffusion model with unprecedented prompt adherence and anatomical fidelity.",
    badge: "PRO",
    inputs: {
      prompt: true,
      negative_prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4", "21:9"],
      resolution: true,
      supported_resolutions: ["1K", "2K"],
      quality: true,
      supported_qualities: ["basic", "high", "extreme"],
    },
    defaultParams: {
      guidance_scale: 3.5,
      num_inference_steps: 28,
    },
  },
  {
    id: "flux-schnell",
    name: "Flux Schnell",
    developer: "Black Forest Labs",
    endpoint: "/flux-schnell",
    category: "t2i",
    description: "Ultra-fast 4-step latent diffusion model engineered for rapid concepting and real-time generation.",
    badge: "FAST",
    inputs: {
      prompt: true,
      negative_prompt: false,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
      resolution: true,
      supported_resolutions: ["1K"],
    },
    defaultParams: {
      num_inference_steps: 4,
    },
  },
  {
    id: "nano-banana",
    name: "Nano Banana",
    developer: "Aether Neural Labs",
    endpoint: "/nano-banana",
    category: "t2i",
    description: "Lightweight, ultra-responsive neural synthesis engine tuned for creative styling and abstract art.",
    badge: "FAST",
    inputs: {
      prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1"],
      resolution: true,
      supported_resolutions: ["1K"],
    },
  },
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    developer: "Aether Neural Labs",
    endpoint: "/nano-banana-2",
    category: "t2i",
    description: "High-definition neural engine with enhanced dynamic range, micro-textures, and up to 4K native output.",
    badge: "HD",
    inputs: {
      prompt: true,
      negative_prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "21:9"],
      resolution: true,
      supported_resolutions: ["1K", "2K", "4K"],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },
  {
    id: "seedream-5-0",
    name: "Seedream 5.0",
    developer: "ByteDance / Seed",
    endpoint: "/seedream-5-0",
    category: "t2i",
    description: "Next-gen spatial transformer model with hyper-realistic human rendering and atmospheric volumetric lighting.",
    badge: "NEW",
    inputs: {
      prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "4:3"],
      resolution: true,
      supported_resolutions: ["2K", "4K"],
    },
  },
  {
    id: "ideogram-v3",
    name: "Ideogram v3",
    developer: "Ideogram AI",
    endpoint: "/ideogram-v3",
    category: "t2i",
    description: "World leader in coherent typography, logo design, graphic composition, and embedded text generation.",
    badge: "PRO",
    inputs: {
      prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "3:4"],
      resolution: true,
      supported_resolutions: ["1K", "2K"],
    },
  },
  {
    id: "midjourney-v7",
    name: "Midjourney v7 Render",
    developer: "Midjourney Architecture",
    endpoint: "/midjourney-v7",
    category: "t2i",
    description: "Artistic master engine providing unparalleled cinematic composition, painterly textures, and color science.",
    badge: "PRO",
    inputs: {
      prompt: true,
      negative_prompt: true,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "21:9"],
      resolution: true,
      supported_resolutions: ["2K", "4K"],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },

  // ==========================================
  // 2. IMAGE-TO-IMAGE (I2I) MULTI-SLOT
  // ==========================================
  {
    id: "nano-banana-2-edit",
    name: "Nano Banana 2 Edit",
    developer: "Aether Neural Labs",
    endpoint: "/nano-banana-2-edit",
    category: "i2i",
    description: "Massive multi-slot reference model accepting up to 14 reference images simultaneously for character and style consistency.",
    badge: "HD",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "images_list",
      maxImages: 14,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "21:9"],
      resolution: true,
      supported_resolutions: ["1K", "2K", "4K"],
    },
  },
  {
    id: "flux-kontext-dev",
    name: "Flux Kontext Dev",
    developer: "Black Forest Labs",
    endpoint: "/flux-kontext-dev",
    category: "i2i",
    description: "Context-aware reference fusion architecture supporting up to 10 subject and background inputs.",
    badge: "PRO",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "images_list",
      maxImages: 10,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1", "4:3"],
      resolution: true,
      supported_resolutions: ["1K", "2K"],
    },
  },
  {
    id: "gpt4o-edit",
    name: "GPT-4o Vision Edit",
    developer: "OpenAI",
    endpoint: "/gpt4o-edit",
    category: "i2i",
    description: "Instructional multi-reference image transformation with deep spatial and semantic understanding.",
    badge: "PRO",
    inputs: {
      prompt: true,
      imageField: "images_list",
      maxImages: 10,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1"],
      resolution: true,
      supported_resolutions: ["1K", "2K"],
    },
  },
  {
    id: "seedream-5-0-edit",
    name: "Seedream 5.0 Edit",
    developer: "ByteDance / Seed",
    endpoint: "/seedream-5-0-edit",
    category: "i2i",
    description: "High-precision compositional transfer blending style, illumination, and identity from up to 10 images.",
    badge: "NEW",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "images_list",
      maxImages: 10,
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1"],
      resolution: true,
      supported_resolutions: ["2K", "4K"],
    },
  },
  {
    id: "neural-upscaler-4k",
    name: "Clarity Neural Upscaler 4K",
    developer: "Aether Neural Labs",
    endpoint: "/upscale-4k",
    category: "i2i",
    description: "Deep generative super-resolution restoring micro-details, sharp edges, and skin pores up to 4K resolution.",
    badge: "HD",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      resolution: true,
      supported_resolutions: ["2K", "4K"],
    },
  },
  {
    id: "bg-remover-matting",
    name: "AI Alpha Matting",
    developer: "Aether Neural Labs",
    endpoint: "/bg-remove",
    category: "i2i",
    description: "Sub-pixel precision alpha mask generation for hair, glass, smoke, and complex transparent subjects.",
    badge: "FAST",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
    },
  },

  // ==========================================
  // 3. TEXT-TO-VIDEO (T2V)
  // ==========================================
  {
    id: "kling-v2-1-t2v",
    name: "Kling v2.1 Cinematic",
    developer: "Kuaishou Kling AI",
    endpoint: "/kling-v2-1-t2v",
    category: "t2v",
    description: "State-of-the-art physics simulation, complex 3D camera sweeps, and high dynamic range 1080p generation.",
    badge: "PRO",
    inputs: {
      prompt: true,
      negative_prompt: true,
      duration: true,
      supported_durations: [5, 10],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1"],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },
  {
    id: "kling-v1-6-t2v",
    name: "Kling v1.6 Fast",
    developer: "Kuaishou Kling AI",
    endpoint: "/kling-v1-6-t2v",
    category: "t2v",
    description: "Fast-iteration video synthesis model optimized for rapid storyboard animatics.",
    badge: "FAST",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16"],
      quality: true,
      supported_qualities: ["basic", "high"],
    },
  },
  {
    id: "sora-2-t2v",
    name: "OpenAI Sora 2",
    developer: "OpenAI",
    endpoint: "/sora-2-t2v",
    category: "t2v",
    description: "World simulator neural model producing long temporal coherence, physics consistency, and photorealism.",
    badge: "PRO",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5, 10, 15],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "21:9"],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },
  {
    id: "veo-3-t2v",
    name: "Google DeepMind Veo 3",
    developer: "Google DeepMind",
    endpoint: "/veo-3-t2v",
    category: "t2v",
    description: "Hollywood-grade cinematic understanding with precise control over lens dynamics, lighting changes, and motion.",
    badge: "PRO",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5, 10],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16"],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },
  {
    id: "wan-2-6-t2v",
    name: "Wan 2.6 Ultra Video",
    developer: "Alibaba Wanx",
    endpoint: "/wan-2-6-t2v",
    category: "t2v",
    description: "Diffusion transformer with robust temporal motion and rich Asian & Western cinematic styles.",
    badge: "NEW",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5, 10],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16", "1:1"],
      quality: true,
      supported_qualities: ["high"],
    },
  },
  {
    id: "seedance-2-0-t2v",
    name: "Seedance 2.0",
    developer: "ByteDance / Seed",
    endpoint: "/seedance-2-0-t2v",
    category: "t2v",
    description: "Complex dynamic choreography and rapid character locomotion engine.",
    badge: "NEW",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5, 10, 15],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16"],
      quality: true,
      supported_qualities: ["basic", "high"],
    },
  },
  {
    id: "grok-imagine-t2v",
    name: "Grok Imagine Motion",
    developer: "xAI",
    endpoint: "/grok-imagine-t2v",
    category: "t2v",
    description: "Unfiltered, dynamic motion engine with humorous and energetic stylized behaviors.",
    badge: "EXPERIMENTAL",
    inputs: {
      prompt: true,
      duration: true,
      supported_durations: [5],
      aspect_ratio: true,
      supported_aspect_ratios: ["16:9", "9:16"],
      mode: true,
      supported_modes: ["normal", "fun", "spicy"],
    },
  },

  // ==========================================
  // 4. IMAGE-TO-VIDEO (I2V) & MOTION BRUSH
  // ==========================================
  {
    id: "kling-i2v",
    name: "Kling I2V Engine",
    developer: "Kuaishou Kling AI",
    endpoint: "/kling-i2v",
    category: "i2v",
    description: "Industry-leading image animation engine supporting localized trajectory vector mapping and brush painting.",
    badge: "PRO",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "image_url",
      maxImages: 1,
      duration: true,
      supported_durations: [5, 10],
      quality: true,
      supported_qualities: ["high", "extreme"],
    },
  },
  {
    id: "veo-3-i2v",
    name: "Veo 3 Image Animator",
    developer: "Google DeepMind",
    endpoint: "/veo-3-i2v",
    category: "i2v",
    description: "Preserves start-frame lighting and spatial depth while simulating physically accurate scene animation.",
    badge: "PRO",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "image_url",
      maxImages: 1,
      duration: true,
      supported_durations: [5, 10],
    },
  },
  {
    id: "runway-gen3-i2v",
    name: "Runway Gen-3 Alpha I2V",
    developer: "Runway",
    endpoint: "/runway-gen3-i2v",
    category: "i2v",
    description: "High-fidelity cinematic transformation from single image with rich fluid dynamics and particle physics.",
    badge: "PRO",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "image_url",
      maxImages: 1,
      duration: true,
      supported_durations: [5, 10],
    },
  },
  {
    id: "wan-2-2-i2v",
    name: "Wan 2.2 I2V Motion",
    developer: "Alibaba Wanx",
    endpoint: "/wan-2-2-i2v",
    category: "i2v",
    description: "Expressive subject motion and optical flow animation for digital paintings and photographs.",
    badge: "FAST",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "image_url",
      maxImages: 1,
      duration: true,
      supported_durations: [5],
    },
  },
  {
    id: "seedance-2-0-i2v",
    name: "Seedance 2.0 I2V",
    developer: "ByteDance / Seed",
    endpoint: "/seedance-2-0-i2v",
    category: "i2v",
    description: "Animate still portraits into expressive dancing, walking, and talking performances.",
    badge: "NEW",
    inputs: {
      prompt: true,
      promptOptional: true,
      imageField: "image_url",
      maxImages: 1,
      duration: true,
      supported_durations: [5, 10],
    },
  },

  // ==========================================
  // 5. LIP SYNC & SPEECH MODELS
  // ==========================================
  {
    id: "infinite-talk-480p",
    name: "Infinite Talk Standard (480p)",
    developer: "Infinite Neural Labs",
    endpoint: "/infinite-talk-480p",
    category: "lipsync",
    description: "Fast-synthesis talking head generator supporting long audio speech tracks up to 2 minutes.",
    badge: "FAST",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["480p"],
    },
  },
  {
    id: "infinite-talk-720p",
    name: "Infinite Talk HD (720p)",
    developer: "Infinite Neural Labs",
    endpoint: "/infinite-talk-720p",
    category: "lipsync",
    description: "High-definition viseme synthesis with natural blink cycles, head micro-tilts, and emotional nuance.",
    badge: "HD",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["720p"],
    },
  },
  {
    id: "infinite-talk-v2v",
    name: "Infinite Talk Video Sync (V2V)",
    developer: "Infinite Neural Labs",
    endpoint: "/infinite-talk-v2v",
    category: "lipsync",
    description: "Full video re-dubbing: syncs existing speaker lips in an MP4 video to a new speech audio track.",
    badge: "PRO",
    inputs: {
      prompt: false,
      videoField: "video_url",
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["720p", "1080p"],
    },
  },
  {
    id: "wan-2-2-speech",
    name: "Wan 2.2 Neural Speech",
    developer: "Alibaba Wanx",
    endpoint: "/wan-2-2-speech",
    category: "lipsync",
    description: "Accurate lip synchronization across multi-lingual phonemes with high acoustic resilience.",
    badge: "NEW",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["720p"],
    },
  },
  {
    id: "ltx-2-3-lipsync",
    name: "LTX 2.3 Expressive LipSync",
    developer: "Lightricks LTX",
    endpoint: "/ltx-2-3-lipsync",
    category: "lipsync",
    description: "Expressive neural voice-to-lip matching with dynamic eye contact and head gesture modeling.",
    badge: "PRO",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["480p", "720p", "1080p"],
    },
  },
  {
    id: "latentsync-pro",
    name: "LatentSync Pro",
    developer: "ByteDance AI",
    endpoint: "/latentsync-pro",
    category: "lipsync",
    description: "Latent-space audio-guided video lip modification with artifact-free boundary blending.",
    badge: "PRO",
    inputs: {
      prompt: false,
      videoField: "video_url",
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["720p", "1080p"],
    },
  },
  {
    id: "creatify-neural",
    name: "Creatify Avatar Voice",
    developer: "Creatify AI",
    endpoint: "/creatify-neural",
    category: "lipsync",
    description: "Avatar marketing speech engine creating crisp, direct-to-camera commercial presenters.",
    badge: "HD",
    inputs: {
      prompt: false,
      imageField: "image_url",
      maxImages: 1,
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["720p"],
    },
  },
  {
    id: "veed-dub-sync",
    name: "Veed Studio Dubber",
    developer: "Veed.io",
    endpoint: "/veed-dub-sync",
    category: "lipsync",
    description: "Studio-grade dubbing re-aligner for multi-lingual translation and audio replacement.",
    badge: "PRO",
    inputs: {
      prompt: false,
      videoField: "video_url",
      audioField: "audio_url",
      resolution: true,
      supported_resolutions: ["1080p"],
    },
  },
];

export function getModelsByCategory(category: string): NeuralModelDefinition[] {
  return MODEL_REGISTRY.filter((m) => m.category === category);
}

export function getModelById(id: string): NeuralModelDefinition | undefined {
  return MODEL_REGISTRY.find((m) => m.id === id);
}

export const T2I_MODELS = getModelsByCategory("t2i");
export const I2I_MODELS = getModelsByCategory("i2i");
export const T2V_MODELS = getModelsByCategory("t2v");
export const I2V_MODELS = getModelsByCategory("i2v");
export const LIPSYNC_MODELS = getModelsByCategory("lipsync");
